### PR TITLE
Capstone project deployment

### PR DESCRIPTION
**Pull request by damdafayton**
- Use ruby gems as software packages system.
- Install Ruby on Rails framework.
- Understand Rails RESTful design and router.
- Use controllers to handle requests and render empty views.
- Use params from browser request in a safe way.
- Use preprocessed html file with embedded Ruby code.
- Use layouts and templates for shared content.
- Use database migration files to maintain database schema.
- Use validations for models.
- Secure app from n+1 problems.
- Understand what ORM is.
- Write SQL queries with ActiveRecord.
- Set up associations between models.
- Build a webapp that requires the user to log in.
- Use devise gem for authentication.
- Limit access to webapp resources based on authorization rules.
- Analyze in writing why you have made a coding choice using one structure over another.

[Video description](https://www.loom.com/share/91804bc711804782ad759795c0e6c4d9)
[Additional explanation](https://www.loom.com/share/ac656052d09b493d9ec2468e01b7771f)

### CODE REVIEW

**Review by OLIPLICHE — CHANGES_REQUESTED** [review]
Hi @damdafayton , 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

## Highlights
Linter result is green ✔️
 Commit messages are meaningful✔️
 The pull request have a descriptive title telling you what changes are inside ✔️
 The pull request have a short summary describing introduced changes in more detail ✔️
 node_modules folder is in the .gitignore ✔️

## Required Changes ♻️

- [x] Please make all your files visible to facilitate inline comments to the code 

- [x] Please make sure the README contains an "Acknowledgements" section or similar that gives appropriate credit to [Gregoire Vella on Behance](https://www.behance.net/gregoirevella) the [author of the original design](https://www.behance.net/gallery/19759151/Snapscan-iOs-design-and-branding?tracking_source=), as required by the [Creative Commons license of the design](https://creativecommons.org/licenses/by-nc/4.0/).

- [x] Please a recorded video presenting the features of the code, It is a recommendation of the project. If it is already done, kindly make the link to the video available.

- [x] Please provide the link to the deployed project in the README: You need deploys the application using Heroku, Netlify or GitHub Pages




## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Review by ShadyShawkat — CHANGES_REQUESTED** [review]
## Hi @damdafayton, 

Great work on making the changes requested by a previous reviewer 👏 
You've done well implementing some of the requested changes, but there are still some which aren't addressed yet.

Image

 ## Required Changes ♻️
- [ ] Kindly make sure that the video contains a highlight some interesting piece of code or something you built that you are very proud of, as per [this](https://github.com/microverseinc/curriculum-rails/blob/main/capstone/rails_capstone.md#:~:text=Once%20you%20have,very%20proud%20of.) requirement.

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by damdafayton** [comment]
> ## Hi @damdafayton,
> Great work on making the changes requested by a previous reviewer 👏 You've done well implementing some of the requested changes, but there are still some which aren't addressed yet.
> 
> Image [ ](https://camo.githubusercontent.com/af57b9be7026ff363ac131f000b15bbb4ff3c4bac1ca3b24b5c730888674d626/68747470733a2f2f632e74656e6f722e636f6d2f43577253424d4c3068433841414141432f6c6974746c652d64696e6f736175722d736f2d636c6f73652e676966) Image [ ](https://camo.githubusercontent.com/af57b9be7026ff363ac131f000b15bbb4ff3c4bac1ca3b24b5c730888674d626/68747470733a2f2f632e74656e6f722e636f6d2f43577253424d4c3068433841414141432f6c6974746c652d64696e6f736175722d736f2d636c6f73652e676966)
> 
> ## Required Changes ♻️
> * [ ]  Kindly make sure that the video contains a highlight some interesting piece of code or something you built that you are very proud of, as per [this](https://github.com/microverseinc/curriculum-rails/blob/main/capstone/rails_capstone.md#:~:text=Once%20you%20have,very%20proud%20of.) requirement.
> 
> ## Optional suggestions
> _Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._
> 
> Cheers and Happy coding!👏👏👏
> 
> Feel free to leave any questions or comments in the PR thread if something is not 100% clear. Please, remember to tag me in your question so I can receive the notification.
> 
> **_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**
> 
> _As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

Hi @ShadyShawkat, I have already mentioned that I made a responsive design which wasn't a requirement but an additional one.

https://www.loom.com/share/ac656052d09b493d9ec2468e01b7771f

**Comment by ShadyShawkat** [comment]
Hey @damdafayton, 

The requirements indicate that you show a piece of your code when you're talking about the feature. You can show the media queries responsible for the responsive design.

**Comment by damdafayton** [comment]
> Hey @damdafayton,
> 
> The requirements indicate that you show a piece of your code when you're talking about the feature. You can show the media queries responsible for the responsive design.

@ShadyShawkat I have no idea what is the purpose of showing code lines in a video. Is that not what github is used for?

**Comment by damdafayton** [comment]
> Hey @damdafayton,
> 
> The requirements indicate that you show a piece of your code when you're talking about the feature. You can show the media queries responsible for the responsive design.

@ShadyShawkat Ok added another video:
https://www.loom.com/share/a35c5a7402734f67b9ce774c29836e13

**Review by ShadyShawkat — APPROVED** [review]
## Hi @damdafayton, 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

Image

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Pull request merged**
